### ISSUE TITLE
reported 100% CPU when running

### ISSUE THREAD

**Issue by Banana5kin** [chinezbrun/pytes_serial#23]
Hi there,

When I run pytes_serial.py one of the RPI cores is constantly at 100%.  It's configured for mysql and mqtt, and I have configured for one or other with no change to cpu usage.  The refresh period is set to 600 seconds so it's not like I am trying to hammer the stats. 

![image](https://github.com/chinezbrun/pytes_serial/assets/15854261/2e7ead87-a6a7-4136-b34b-aaa032b0328a)

I ran py-spy to monitor the running python code with the results below.

![image](https://github.com/chinezbrun/pytes_serial/assets/15854261/42d1b8ac-19f7-4608-8bb9-186d94918b5a)

Many thanks.

**Comment by chinezbrun** [comment]
Could you please  provide  more  info ref your configuration i.e python, modules version used etc.
