### ISSUE TITLE
FEATURE REQUEST: PACK CYCLES

### ISSUE THREAD

**Issue by networkerict** [chinezbrun/pytes_serial#39]
I would love to see the number of cycles of each battery (Pylontech US5000-1C).

Thanks for the support! Much appreciated!

**Comment by chinezbrun** [comment]
Thanks for your sugestion. There was alway a difficult decision between implementing a new feature and complexity / stability. In this case i will  chose stability :) i already close some similar request #36 , #37.

**Comment by chinezbrun** [comment]
I will now close this issue as it is unlikely to be implemented in the near future. Thank you for the suggestion and even if it was not implemented, I hope you like the new version of the program.
