### ISSUE TITLE
authentication for mqtt home assistant 

### ISSUE THREAD

**Issue by hurly85** [chinezbrun/pytes_serial#7]
Hi, thanks for your great script, i got it working on my raspberry pi. The only thing i am struggling with is the mqtt connection to home assistant. In the pytes_serial.cfg i set mqtt to active and i added the local ip address of my home assistant server.
In the script i get the error: mqtt publish errorConnection Refused: not authorised
How or where can i add my mqtt broker credentials to your script?

**Comment by chinezbrun** [comment]
you need to have an MQTT_broker up and running (i.e Mosquito). Home Assistant is a MQTT client.   I have Eclipse Mosquito installed on my Synology NAS. You can try also Home assistant add on here [Mosquitto](url) -- never used or alternanive for Raspberry PI.

**Comment by hurly85** [comment]
Thanks for your answer, i have mosquito integration installed on home assistant and more then 20 devices connected. The issue is that my home assistant mqtt integration requests user and password when a mqtt device tries to connect. I will test it with a another mqtt broker as i am playing arround with my mqtt integration on home assistant and i can´t get anonymous mqtt devices to connect. Do you use your mqtt broker without authentication?

**Comment by chinezbrun** [comment]
yes i'm using mqtt broker w/o authentication. all tests were done without authentication.

**Comment by hurly85** [comment]
Thanks sorry for my absense, yes i will try it

**Comment by hurly85** [comment]
Hi, i tested it and it worked, thanks a lot

**Comment by chinezbrun** [comment]
thanks of spot it out this opportunity. please confirm the pytes_serial version used.

**Comment by hurly85** [comment]
Great work the script is running all night without error, see pics attached
![20230127_083347](https://user-images.githubusercontent.com/111656314/215032946-e554d410-3bc6-4c9b-b11b-627fe1714aaf.jpg)
![20230127_083529](https://user-images.githubusercontent.com/111656314/215032952-59d7148d-eef1-474c-aab6-5b0e9b6e6b14.jpg)

**Comment by chinezbrun** [comment]
super!
